[mypy]
python_version = 3.12
warn_return_any = True
warn_unused_configs = True
ignore_missing_imports = True
exclude = (migrations|venv|\.venv)

[mypy-django.*]
ignore_missing_imports = True

[mypy-apps.*]
ignore_errors = True
